name: subtitle_wrapper
description: A Subtitle Wrapper package, this subtitle wrapper package displays subtitles for a vlc player.
version: 0.0.4
homepage: https://github.com/caua-n/subtitles_wrapper

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  http: ^1.2.1
  http_parser: ^4.0.2
  flutter_vlc_player: ^7.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
